package txtypes

import "fmt"

var (
	ErrAccountIndexTooLow         = fmt.Errorf("AccountIndex should not be less than %d", minAccountIndex)
	ErrAccountIndexTooHigh        = fmt.Errorf("AccountIndex should not be larger than %d", maxAccountIndex)
	ErrGasAccountIndexTooLow      = fmt.Errorf("GasAccountIndex should not be less than %d", minAccountIndex)
	ErrGasAccountIndexTooHigh     = fmt.Errorf("GasAccountIndex should not be larger than %d", maxAccountIndex)
	ErrGasFeeAssetIdTooLow        = fmt.Errorf("GasFeeAssetId should not be less than %d", minAssetId)
	ErrGasFeeAssetIdTooHigh       = fmt.Errorf("GasFeeAssetId should not be larger than %d", maxAssetId)
	ErrGasFeeAssetAmountTooLow    = fmt.Errorf("GasFeeAssetAmount should not be less than %s", minPackedFeeAmount.String())
	ErrGasFeeAssetAmountTooHigh   = fmt.Errorf("GasFeeAssetAmount should not be larger than %s", maxPackedFeeAmount.String())
	ErrGasFeeAssetAmountPrecision = fmt.Errorf("GasFeeAssetAmount precision is invalid")
	ErrNonceTooLow                = fmt.Errorf("Nonce should not be less than %d", minNonce)
	ErrOfferTypeInvalid           = fmt.Errorf("Type should only be buy(%d) and sell(%d)", BuyOfferType, SellOfferType)
	ErrOfferIdTooLow              = fmt.Errorf("OfferId should not be less than 0")
	ErrNftIndexTooLow             = fmt.Errorf("NftIndex should not be less than %d", minNftIndex)
	ErrNftIndexTooHigh            = fmt.Errorf("NftIndex should not be larger than %d", maxNftIndex)
	ErrAssetIdTooLow              = fmt.Errorf("AssetId should not be less than %d", minAssetId)
	ErrAssetIdTooHigh             = fmt.Errorf("AssetId should not be larger than %d", maxAssetId)
	ErrAssetAmountTooLow          = fmt.Errorf("AssetAmount should be larger than %s", minAssetAmount.String())
	ErrAssetAmountTooHigh         = fmt.Errorf("AssetAmount should not be larger than %s", maxAssetAmount.String())
	ErrAssetAmountPrecision       = fmt.Errorf("AssetAmount precision is invalid")
	ErrProtocolAmountTooLow       = fmt.Errorf("ProtocolAmount should be larger than %s", minAssetAmount.String())
	ErrProtocolAmountTooHigh      = fmt.Errorf("ProtocolAmount should not be larger than %s", maxAssetAmount.String())
	ErrProtocolAmountPrecision    = fmt.Errorf("ProtocolAmount precision is invalid")
	ErrProtocolAmountInvalid      = fmt.Errorf("invalid platform amount")
	ErrListedAtTooLow             = fmt.Errorf("ListedAt should be larger than 0")
	ErrChannelRateTooLow          = fmt.Errorf("ChannelRate should  not be less than %d", minRate)
	ErrChannelRateTooHigh         = fmt.Errorf("ChannelRate should  not be larger than %d", maxRate)
	ErrChannelAmountPrecision     = fmt.Errorf("ChannelAmount is from ChannelRate * AssetAmount,but this precision is invalid")
	ErrProtocolRateTooLow         = fmt.Errorf("ProtocolRate should  not be less than %d", minRate)
	ErrProtocolRateTooHigh        = fmt.Errorf("ProtocolRate should  not be larger than %d", maxRate)
	ErrCollectionNameTooShort     = fmt.Errorf("length of Name should not be less than %d", minCollectionNameLength)
	ErrCollectionNameTooLong      = fmt.Errorf("length of Name should not be larger than %d", maxCollectionNameLength)
	ErrIntroductionTooLong        = fmt.Errorf("length of Introduction should not be larger than %d", maxCollectionIntroductionLength)
	ErrNftContentHashInvalid      = fmt.Errorf("NftContentHash is invalid")
	ErrNftCollectionIdTooLow      = fmt.Errorf("NftCollectionId should not be less than %d", minCollectionId)
	ErrNftCollectionIdTooHigh     = fmt.Errorf("NftCollectionId should not be larger than %d", maxCollectionId)
	ErrNftContentTypeTooLow       = fmt.Errorf("NftCollectionId should not be less than %d", minNftContentType)
	ErrNftContentTypeTooHigh      = fmt.Errorf("NftCollectionId should not be larger than %d", maxNftContentType)
	ErrCallDataHashInvalid        = fmt.Errorf("CallDataHash is invalid")
	ErrCallDataInvalid            = fmt.Errorf("CallData should not be larger than %d", maxLength)
	ErrMemoInvalid                = fmt.Errorf("Memo should not be larger than %d", maxLength)
	ErrPubKeyXYInvalid            = fmt.Errorf("PubKeyX or PubKeyY is invalid")

	ErrCreatorAccountIndexTooLow  = fmt.Errorf("CreatorAccountIndex should not be less than %d", minAccountIndex)
	ErrCreatorAccountIndexTooHigh = fmt.Errorf("CreatorAccountIndex should not be larger than %d", maxAccountIndex)
	ErrToAccountIndexTooLow       = fmt.Errorf("ToAccountIndex should not be less than %d", minAccountIndex)
	ErrToAccountIndexTooHigh      = fmt.Errorf("ToAccountIndex should not be larger than %d", maxAccountIndex)
	ErrToL1AddressInvalid         = fmt.Errorf("ToL1Address is invalid")
	ErrRoyaltyRateTooLow          = fmt.Errorf("RoyaltyRate should  not be less than %d", minRate)
	ErrRoyaltyRateTooHigh         = fmt.Errorf("RoyaltyRate should not be larger than %d", maxRate)
	ErrRoyaltyAmountPrecision     = fmt.Errorf("RoyaltyAmount is from RoyaltyRate * AssetAmount,but this precision is invalid")
	ErrFromAccountIndexTooLow     = fmt.Errorf("FromAccountIndex should not be less than %d", minAccountIndex)
	ErrFromAccountIndexTooHigh    = fmt.Errorf("FromAccountIndex should not be larger than %d", maxAccountIndex)
	ErrToAddressInvalid           = fmt.Errorf("ToAddress is invalid")
	ErrBuyOfferInvalid            = fmt.Errorf("BuyOffer is invalid")
	ErrSellOfferInvalid           = fmt.Errorf("SellOffer is invalid")
)
